### Merge Function

In [1]:
import pandas as pd
import numpy as np

In [2]:
df1 = pd.DataFrame({
    'emp_id':[1,2,3,4],
    'name':['A','B','C','D'],
    'dept_id':[10,20,30,40]
})

df2 = pd.DataFrame({
    'dept_id':[10,20,30],
    'dept_name':['HR','IT','Finance']
})
print(df1)
print(df2)

   emp_id name  dept_id
0       1    A       10
1       2    B       20
2       3    C       30
3       4    D       40
   dept_id dept_name
0       10        HR
1       20        IT
2       30   Finance

In [3]:
pd.merge(df1,df2,on='dept_id',how='inner') # This line merges the two DataFrames, df1 and df2, based on the common column 'dept_id'. The on='dept_id' parameter specifies that the merge should be performed using the 'dept_id' column as the key. The how='inner' parameter indicates that only the rows with matching 'dept_id' values in both DataFrames will be included in the resulting merged DataFrame. If there are any 'dept_id' values in df1 that do not have a corresponding match in df2, or vice versa, those rows will be excluded from the final result.

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance

In [4]:
pd.merge(df1,df2,on='dept_id',how='left')  # This line merges the two DataFrames, df1 and df2, based on the common column 'dept_id'. The on='dept_id' parameter specifies that the merge should be performed using the 'dept_id' column as the key. The how='left' parameter indicates that all rows from df1 will be included in the resulting merged DataFrame, and matching rows from df2 will be included where available. If there are any 'dept_id' values in df1 that do not have a corresponding match in df2, those rows will still be included in the final result, but the columns from df2 will contain NaN values for those unmatched rows.

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance
3       4    D       40       NaN

In [5]:
pd.merge(df1,df2,on='dept_id',how='right')   # This line merges the two DataFrames, df1 and df2, based on the common column 'dept_id'. The on='dept_id' parameter specifies that the merge should be performed using the 'dept_id' column as the key. The how='right' parameter indicates that all rows from df2 will be included in the resulting merged DataFrame, and matching rows from df1 will be included where available. If there are any 'dept_id' values in df2 that do not have a corresponding match in df1, those rows will still be included in the final result, but the columns from df1 will contain NaN values for those unmatched rows.

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance

In [6]:
pd.merge(df1,df2,on='dept_id',how='outer') # This line merges the two DataFrames, df1 and df2, based on the common column 'dept_id'. The on='dept_id' parameter specifies that the merge should be performed using the 'dept_id' column as the key. The how='outer' parameter indicates that all rows from both DataFrames will be included in the resulting merged DataFrame. If there are any 'dept_id' values in df1 that do not have a corresponding match in df2, those rows will still be included in the final result with NaN values for the columns from df2. Similarly, if there are any 'dept_id' values in df2 that do not have a corresponding match in df1, those rows will also be included with NaN values for the columns from df1.

   emp_id name  dept_id dept_name
0       1    A       10        HR
1       2    B       20        IT
2       3    C       30   Finance
3       4    D       40       NaN

In [7]:
pd.merge(df1,df2,how='cross')  # This line merges the two DataFrames, df1 and df2, using a cross join. A cross join produces the Cartesian product of the two DataFrames, meaning each row from df1 will be combined with every row from df2. The resulting DataFrame will have a row for each possible combination of rows from the two input DataFrames. The on parameter is not needed for a cross join, as it does not require a common key between the DataFrames. The resulting DataFrame will contain all columns from both df1 and df2, and the number of rows will be equal to the product of the number of rows in df1 and df2.

    emp_id name  dept_id_x  dept_id_y dept_name
0        1    A         10         10        HR
1        1    A         10         20        IT
2        1    A         10         30   Finance
3        2    B         20         10        HR
4        2    B         20         20        IT
5        2    B         20         30   Finance
6        3    C         30         10        HR
7        3    C         30         20        IT
8        3    C         30         30   Finance
9        4    D         40         10        HR
10       4    D         40         20        IT
11       4    D         40         30   Finance

In [8]:
df1=pd.DataFrame({
    'emp_id':[1,2],
    'name':['A','B'],
    'dept_id':[10,20]
})

df2=pd.DataFrame({
    'd_id':[10,20],
    'dept_name':['HR','IT']
})
print(df1)
print(df2)
df1,df2

   emp_id name  dept_id
0       1    A       10
1       2    B       20
   d_id dept_name
0    10        HR
1    20        IT

(   emp_id name  dept_id
 0       1    A       10
 1       2    B       20,
    d_id dept_name
 0    10        HR
 1    20        IT)

In [9]:
pd.merge(df1,df2,left_on='dept_id',right_on='d_id') # This line merges the two DataFrames, df1 and df2, based on the specified columns. The left_on='dept_id' parameter indicates that the merge should use the 'dept_id' column from df1 as the key, while the right_on='d_id' parameter indicates that the merge should use the 'd_id' column from df2 as the key. The resulting DataFrame will contain all columns from both df1 and df2, and rows will be matched based on the values in these specified columns. If there are any values in 'dept_id' from df1 that do not have a corresponding match in 'd_id' from df2, or vice versa, those rows will be excluded from the final result by default (inner join).

   emp_id name  dept_id  d_id dept_name
0       1    A       10    10        HR
1       2    B       20    20        IT

In [10]:
df1=pd.DataFrame({
    'emp_id':[1,2,3],
    'name':['A','B','C'],
    'dept_id':[10,20,30]
})

df2=pd.DataFrame({
    'd_id':[10,20],
    'dept_name':['HR','IT']
})
print(df1)
print(df2)

   emp_id name  dept_id
0       1    A       10
1       2    B       20
2       3    C       30
   d_id dept_name
0    10        HR
1    20        IT

In [11]:
pd.merge(df1,df2,left_index=True,right_index=True) # This line merges the two DataFrames, df1 and df2, based on their index. The left_index=True parameter indicates that the merge should use the index of df1 as the key, while the right_index=True parameter indicates that the merge should use the index of df2 as the key. The resulting DataFrame will contain all columns from both df1 and df2, and rows will be matched based on their index values. If there are any index values in df1 that do not have a corresponding match in df2, or vice versa, those rows will be excluded from the final result by default (inner join).

   emp_id name  dept_id  d_id dept_name
0       1    A       10    10        HR
1       2    B       20    20        IT

In [12]:
pd.merge(df1,df2,left_index=True,right_index=True,how='outer')

   emp_id name  dept_id  d_id dept_name
0       1    A       10  10.0        HR
1       2    B       20  20.0        IT
2       3    C       30   NaN       NaN

In [13]:
pd.merge(df1,df2,left_index=True,right_index=True,suffixes=['_emp','_dept']) # This line merges the two DataFrames, df1 and df2, based on their index, similar to the previous merge. The left_index=True and right_index=True parameters indicate that the merge should use the index of both DataFrames as the key. The suffixes=['_emp','_dept'] parameter specifies that if there are any overlapping column names between df1 and df2 (other than the index), they will be renamed in the resulting merged DataFrame by appending '_emp' to columns from df1 and '_dept' to columns from df2. This helps to avoid confusion and allows you to distinguish between columns that originated from each DataFrame in the merged result.

   emp_id name  dept_id  d_id dept_name
0       1    A       10    10        HR
1       2    B       20    20        IT

In [14]:
pd.merge(df1,df2,left_index=True,right_index=True,how='outer',sort=True)

   emp_id name  dept_id  d_id dept_name
0       1    A       10  10.0        HR
1       2    B       20  20.0        IT
2       3    C       30   NaN       NaN

### Groupby (Most Useful Function in Pandas)

In [15]:
data = {
    'Department':['IT','IT','HR','HR','FINANCE','IT'],
    'Employee':['A','B','C','D','E','F'],
    'Salary':[50000,60000,45000,48000,70000,55000],
    'Experiance':[2,3,1,2,5,4]
}
df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experiance
0         IT        A   50000           2
1         IT        B   60000           3
2         HR        C   45000           1
3         HR        D   48000           2
4    FINANCE        E   70000           5
5         IT        F   55000           4

In [16]:
df.groupby('Department')

In [17]:
df.groupby('Department').mean(numeric_only=True)

             Salary  Experiance
Department
FINANCE     70000.0         5.0
HR          46500.0         1.5
IT          55000.0         3.0

In [ ]:
df.drop('Employee',axis=1).groupby('Department').agg(['max','mean','sum'])  # This line of code performs a groupby operation on the DataFrame df based on the 'Department' column. It first drops the 'Employee' column from the DataFrame using df.drop('Employee', axis=1), which removes the specified column. Then, it groups the remaining data by the 'Department' column using groupby('Department'). Finally, it applies the agg function to calculate the maximum (max), mean (mean), and sum (sum) for each numeric column in the grouped DataFrame. The resulting output will show these aggregated statistics for each department, excluding the 'Employee' column from the calculations.

           Salary                  Experiance
              max     mean     sum        max mean sum
Department
FINANCE     70000  70000.0   70000          5  5.0   5
HR          48000  46500.0   93000          2  1.5   3
IT          60000  55000.0  165000          4  3.0   9

In [19]:
df.groupby(['Department','Employee']).sum()

                     Salary  Experiance
Department Employee
FINANCE    E          70000           5
HR         C          45000           1
           D          48000           2
IT         A          50000           2
           B          60000           3
           F          55000           4

In [20]:
data = {
    'Department':['IT','IT','HR','HR','FINANCE','IT'],
    'Employee':['A','B','C','D','E','A'],
    'Salary':[50000,60000,45000,48000,70000,55000],
    'Experiance':[2,3,1,2,5,4]
}
df=pd.DataFrame(data)
print(df)

  Department Employee  Salary  Experiance
0         IT        A   50000           2
1         IT        B   60000           3
2         HR        C   45000           1
3         HR        D   48000           2
4    FINANCE        E   70000           5
5         IT        A   55000           4

In [21]:
df.groupby(['Department','Employee']).sum()

                     Salary  Experiance
Department Employee
FINANCE    E          70000           5
HR         C          45000           1
           D          48000           2
IT         A         105000           6
           B          60000           3

In [ ]:
df.groupby('Department',as_index=False,sort=False).sum(numeric_only=True) # This line of code performs a groupby operation on the DataFrame df based on the 'Department' column. The as_index=False parameter indicates that the 'Department' column should not be set as the index in the resulting grouped DataFrame, allowing it to remain as a regular column. The sort=False parameter specifies that the groups should not be sorted by the 'Department' values in the output. Finally, the sum(numeric_only=True) function is applied to calculate the sum of all numeric columns for each department, while ignoring any non-numeric columns. The resulting output will show the total salary and experience for each department without sorting or setting 'Department' as the index.

  Department  Salary  Experiance
0         IT  165000           9
1         HR   93000           3
2    FINANCE   70000           5

In [23]:
df.groupby('Department')['Salary'].mean()

Department
FINANCE    70000.0
HR         46500.0
IT         55000.0
Name: Salary, dtype: float64

In [ ]:
df.groupby('Department').agg({'Salary':['max','mean','median'],
                             'Experiance':'mean'}) # This line of code performs a groupby operation on the DataFrame df based on the 'Department' column. It then applies the agg function to calculate specific aggregated statistics for the 'Salary' and 'Experiance' columns. For the 'Salary' column, it calculates the maximum (max), mean (mean), and median (median) values for each department. For the 'Experiance' column, it calculates the mean value for each department. The resulting output will show these aggregated statistics for each department, allowing you to analyze the salary distribution and average experience within each department.

           Salary                   Experiance
              max     mean   median       mean
Department
FINANCE     70000  70000.0  70000.0        5.0
HR          48000  46500.0  46500.0        1.5
IT          60000  55000.0  55000.0        3.0

In [25]:
df.groupby('Department').size()

Department
FINANCE    1
HR         2
IT         3
dtype: int64

In [26]:
df.groupby('Department').count()

            Employee  Salary  Experiance
Department
FINANCE            1       1           1
HR                 2       2           2
IT                 3       3           3

In [27]:
df.groupby('Department').describe()

           Salary                                                            \
            count     mean          std      min      25%      50%      75%
Department
FINANCE       1.0  70000.0          NaN  70000.0  70000.0  70000.0  70000.0
HR            2.0  46500.0  2121.320344  45000.0  45750.0  46500.0  47250.0
IT            3.0  55000.0  5000.000000  50000.0  52500.0  55000.0  57500.0

                    Experiance
                max      count mean       std  min   25%  50%   75%  max
Department
FINANCE     70000.0        1.0  5.0       NaN  5.0  5.00  5.0  5.00  5.0
HR          48000.0        2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0
IT          60000.0        3.0  3.0  1.000000  2.0  2.50  3.0  3.50  4.0

In [ ]:
df.groupby('Department').nth(0) # This line of code performs a groupby operation on the DataFrame df based on the 'Department' column and then selects the first row (nth(0)) from each group. The nth() function is used to retrieve a specific row from each group, where the argument specifies the position of the row to be selected. In this case, nth(0) selects the first row from each department group. The resulting output will show one representative row for each department, which can be useful for quickly inspecting the data or for further analysis.

  Department Employee  Salary  Experiance
0         IT        A   50000           2
2         HR        C   45000           1
4    FINANCE        E   70000           5

In [ ]:
df.groupby('Department').nth(1)
# The nth(1) function selects the second row from each department group in the DataFrame df. Similar to nth(0), which selects the first row, nth(1) retrieves the row at index position 1 (the second row) for each group defined by the 'Department' column. The resulting output will show one representative row for each department, specifically the second entry for each department group. If a department has fewer than two entries, it will return NaN for that department in the output.

  Department Employee  Salary  Experiance
1         IT        B   60000           3
3         HR        D   48000           2

In [30]:
def fun(x):
    x['Highest_Earner'] = x['Salary']>x['Salary'].mean()
    return x
df_new=df.groupby('Department').apply(fun)
df_new

C:\Users\dhruv\AppData\Local\Temp\ipykernel_20892\1704087626.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_new=df.groupby('Department').apply(fun)

             Department Employee  Salary  Experiance  Highest_Earner
Department
FINANCE    4    FINANCE        E   70000           5           False
HR         2         HR        C   45000           1           False
           3         HR        D   48000           2            True
IT         0         IT        A   50000           2           False
           1         IT        B   60000           3            True
           5         IT        A   55000           4           False

In [31]:
group=df.groupby('Department')
group.get_group('IT')

  Department Employee  Salary  Experiance
0         IT        A   50000           2
1         IT        B   60000           3
5         IT        A   55000           4