## Columns and Their Descriptions 
- ID: Unique match identifier. 
- City: City where the match was played (may contain missing values). 
- Date: Date of the match. 
- Season: IPL season year (e.g., 2008, 2022). 
- MatchNumber: Match number in the respective season. 
- Team1: Name of the first team in the match. 
- Team2: Name of the second team in the match. 
- Venue: Stadium or ground where the match was held. 
- TossWinner: Team that won the toss. 
- TossDecision: Toss decision taken (bat or bowl). 
- SuperOver: Indicates if a Super Over was played (Yes/No). 
- WinningTeam: Team that won the match. 
- WonBy: Indicates if the match was won by runs or wickets. 
- Margin: Margin of victory (runs or wickets). 
- method: Method used to determine results in interrupted matches (e.g., Duckworth-Lewis, rarely present). 
- Player_of_Match: Player who was awarded "Player of the Match". 
- Team1Players: List of players in Team 1. 
- Team2Players: List of players in Team 2. 
- Umpire1: Name of the first on-field umpire. 
- Umpire2: Name of the second on-field umpire.

In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv('ipl-matches.csv')
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

### Standardization of Team Names (Franchise Renaming) 
- In  the  given  dataset,  some  IPL  teams  are  listed  using  their  old  franchise  names. 
- You are required to standardize the team names by replacing them with their updated official names. 
- ``` Old Name → New Name Mapping:  ```
    - Delhi Daredevils → Delhi Capitals  
    - Kings XI Punjab → Punjab Kings  
    - Rising Pune Supergiants → Rising Pune Supergiant

In [2]:
df.replace(['Delhi Daredevils','Kings XI Punjab','Rising Pune Supergiants'],
          ['Delhi Capitals','Punjab Kings','Rising Pune Supergiant'],
          inplace=True)
df

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Capitals,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Capitals,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Punjab Kings,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

### Identify the Top Winning Team per Season 
- For every season: 
    - Identify the team with the highest number of wins  
    -  Display:  
        - Season  
        - Winning Team (with maximum wins)  
        - Number of Wins 
    - Output format (DataFrame columns): 

``` Season | WinningTeam | number_of_wins ```

In [19]:
season_wins = (
    df.dropna(subset=['WinningTeam'])
      .groupby(['Season', 'WinningTeam'])
      .size()
      .reset_index(name='number_of_wins')
      .sort_values(['Season', 'number_of_wins'], ascending=[True, False])
      .drop_duplicates(subset='Season')
      .reset_index(drop=True)
)

season_wins

     Season            WinningTeam  number_of_wins
0   2007/08       Rajasthan Royals              13
1      2009         Delhi Capitals              10
2   2009/10         Mumbai Indians              11
3      2011    Chennai Super Kings              11
4      2012  Kolkata Knight Riders              12
5      2013         Mumbai Indians              13
6      2014           Punjab Kings              12
7      2015    Chennai Super Kings              10
8      2016    Sunrisers Hyderabad              11
9      2017         Mumbai Indians              12
10     2018    Chennai Super Kings              11
11     2019         Mumbai Indians              11
12  2020/21         Mumbai Indians              11
13     2021    Chennai Super Kings              11
14     2022         Gujarat Titans              12

### Player of the Match Diversity per Winning Team 
- For each winning team: 
    - Calculate the number of unique players who received the Player of the Match award  
    - Display the diversity count for each team  
    - Arrange the results in descending order of diversity 
    - Output format (DataFrame columns): 
 
``` WinningTeam | number_of_unique_player ```

In [16]:
ab=df.groupby('WinningTeam')['Player_of_Match'].nunique().sort_values(ascending=False).reset_index(name='number_of_unique_players')
ab

                    WinningTeam  number_of_unique_players
0                Delhi Capitals                        50
1                  Punjab Kings                        49
2         Kolkata Knight Riders                        44
3                Mumbai Indians                        43
4              Rajasthan Royals                        41
5           Chennai Super Kings                        39
6   Royal Challengers Bangalore                        36
7           Sunrisers Hyderabad                        36
8               Deccan Chargers                        19
9                 Pune Warriors                        11
10               Gujarat Titans                         9
11       Rising Pune Supergiant                         9
12                Gujarat Lions                         7
13         Lucknow Super Giants                         6
14         Kochi Tuskers Kerala                         4

### Display Teams by Match Wins Based on Toss Decision (Descending Order )
- For each toss decision: 
    - Calculate the number of matches won by each team. 
    - Display the results in descending order of wins. 
    - Output format (DataFrame columns): 
 
``` TossDecision | WinningTeam | wins ```

In [14]:
ab = (
    df.groupby(['TossDecision', 'WinningTeam'])
      .size()
      .reset_index(name='wins')
      .sort_values(['TossDecision', 'wins'], ascending=[True, False])
      .reset_index(drop=True)
)
ab

   TossDecision                  WinningTeam  wins
0           bat          Chennai Super Kings    59
1           bat               Mumbai Indians    52
2           bat        Kolkata Knight Riders    42
3           bat             Rajasthan Royals    40
4           bat               Delhi Capitals    37
5           bat  Royal Challengers Bangalore    35
6           bat                 Punjab Kings    26
7           bat          Sunrisers Hyderabad    25
8           bat              Deccan Chargers    14
9           bat                Pune Warriors     9
10          bat               Gujarat Titans     5
11          bat                Gujarat Lions     2
12          bat         Lucknow Super Giants     2
13          bat       Rising Pune Supergiant     2
14        field               Mumbai Indians    79
15        field                 Punjab Kings    75
16        field  Royal Challengers Bangalore    74
17        field        Kolkata Knight Riders    72
18        field               Delhi Capitals    66
19        field          Chennai Super Kings    62
20        field             Rajasthan Royals    56
21        field          Sunrisers Hyderabad    50
22        field              Deccan Chargers    15
23        field       Rising Pune Supergiant    13
24        field                Gujarat Lions    11
25        field               Gujarat Titans     7
26        field         Lucknow Super Giants     7
27        field         Kochi Tuskers Kerala     6
28        field                Pune Warriors     3

### Analysis of Top Five Venues with Highest Match Frequency and Their Dominant Winning Teams 
(Descending Order) 
-  Identify the top 5 venues where the highest number of matches have been played 
-  For each of these venues: 
    - Calculate which team has won the most matches at that venue 
    - Display the dominant team along with the number of wins 
        -  Sort the results in descending order of winning matches 
        - Output format (DataFrame columns): 
        
``` Venue | WinningTeam | no_of_winning_match ```

In [20]:
top_venues = df['Venue'].value_counts().head(5).index

venue_dominant_team = (
    df[df['Venue'].isin(top_venues)]
    .dropna(subset=['WinningTeam'])
    .groupby(['Venue', 'WinningTeam'])
    .size()
    .reset_index(name='no_of_winning_match')
    .sort_values(['Venue', 'no_of_winning_match'], ascending=[True, False])
    .drop_duplicates(subset='Venue')
    .sort_values('no_of_winning_match', ascending=False)
    .reset_index(drop=True)
)

venue_dominant_team

,Venue,WinningTeam,no_of_winning_match
0,Eden Gardens,Kolkata Knight Riders,45
1,Wankhede Stadium,Mumbai Indians,42
2,M Chinnaswamy Stadium,Royal Challengers Bangalore,29
3,Feroz Shah Kotla,Delhi Capitals,23
4,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,20

### All Season-wise IPL Points Table Generation 
- For each season output in data frame: 
    - Calculate the total number of matches played by each team  
    - Calculate the total number of matches won by each team  
    - Identify matches with no result  
    - Compute total points using:  
        - Win = 2 points  
        - No Result = 1 point  
    - sorting teams based on points in descending order 
- Output format (example): 
``` 
Season: 2022                                                               
Team Name                  Matches Played  Matches Won  No Result  Points  
Gujarat Titans                         16           12          0      24  

```

In [21]:
# Season-wise points table

matches_played = (
    df.melt(id_vars=['Season'], value_vars=['Team1', 'Team2'], value_name='Team')
      .groupby(['Season', 'Team'])
      .size()
      .reset_index(name='Matches Played')
)

matches_won = (
    df.dropna(subset=['WinningTeam'])
      .groupby(['Season', 'WinningTeam'])
      .size()
      .reset_index(name='Matches Won')
      .rename(columns={'WinningTeam': 'Team'})
)

no_result = (
    df[df['WinningTeam'].isna()]
      .melt(id_vars=['Season'], value_vars=['Team1', 'Team2'], value_name='Team')
      .groupby(['Season', 'Team'])
      .size()
      .reset_index(name='No Result')
)

points_table = (
    matches_played
    .merge(matches_won, on=['Season', 'Team'], how='left')
    .merge(no_result, on=['Season', 'Team'], how='left')
    .fillna(0)
)

points_table[['Matches Won', 'No Result']] = points_table[['Matches Won', 'No Result']].astype(int)
points_table['Points'] = points_table['Matches Won'] * 2 + points_table['No Result']

points_table = (
    points_table
    .rename(columns={'Team': 'Team Name'})
    .sort_values(['Season', 'Points', 'Matches Won'], ascending=[True, False, False])
    .reset_index(drop=True)
)

# Optional: display season-wise like the requested format
for season, season_df in points_table.groupby('Season', sort=True):
    print(f"Season: {season}")
    display(season_df[['Team Name', 'Matches Played', 'Matches Won', 'No Result', 'Points']].reset_index(drop=True))

Season: 2007/08

                     Team Name  Matches Played  Matches Won  No Result  Points
0             Rajasthan Royals              16           13          0      26
1                 Punjab Kings              15           10          0      20
2          Chennai Super Kings              16            9          0      18
3               Delhi Capitals              14            7          0      14
4               Mumbai Indians              14            7          0      14
5        Kolkata Knight Riders              13            6          0      12
6  Royal Challengers Bangalore              14            4          0       8
7              Deccan Chargers              14            2          0       4

Season: 2009

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Delhi Capitals              15           10          0      20
1              Deccan Chargers              16            9          0      18
2  Royal Challengers Bangalore              16            9          0      18
3          Chennai Super Kings              14            8          0      16
4                 Punjab Kings              14            7          0      14
5             Rajasthan Royals              13            6          0      12
6               Mumbai Indians              13            5          0      10
7        Kolkata Knight Riders              13            3          0       6

Season: 2009/10

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Mumbai Indians              16           11          0      22
1          Chennai Super Kings              16            9          0      18
2              Deccan Chargers              16            8          0      16
3  Royal Challengers Bangalore              16            8          0      16
4               Delhi Capitals              14            7          0      14
5        Kolkata Knight Riders              14            7          0      14
6             Rajasthan Royals              14            6          0      12
7                 Punjab Kings              14            4          0       8

Season: 2011

                     Team Name  Matches Played  Matches Won  No Result  Points
0          Chennai Super Kings              16           11          0      22
1               Mumbai Indians              16           10          0      20
2  Royal Challengers Bangalore              16           10          0      20
3        Kolkata Knight Riders              15            8          0      16
4                 Punjab Kings              14            7          0      14
5              Deccan Chargers              14            6          0      12
6         Kochi Tuskers Kerala              14            6          0      12
7             Rajasthan Royals              13            6          0      12
8               Delhi Capitals              14            4          1       9
9                Pune Warriors              14            4          1       9

Season: 2012

                     Team Name  Matches Played  Matches Won  No Result  Points
0        Kolkata Knight Riders              17           12          0      24
1               Delhi Capitals              18           11          0      22
2          Chennai Super Kings              18           10          0      20
3               Mumbai Indians              17           10          0      20
4                 Punjab Kings              16            8          0      16
5  Royal Challengers Bangalore              15            8          0      16
6             Rajasthan Royals              16            7          0      14
7              Deccan Chargers              15            4          0       8
8                Pune Warriors              16            4          0       8

Season: 2013

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Mumbai Indians              19           13          0      26
1          Chennai Super Kings              18           12          0      24
2             Rajasthan Royals              18           11          0      22
3          Sunrisers Hyderabad              17           10          0      20
4  Royal Challengers Bangalore              16            9          0      18
5                 Punjab Kings              16            8          0      16
6        Kolkata Knight Riders              16            6          0      12
7                Pune Warriors              16            4          0       8
8               Delhi Capitals              16            3          0       6

Season: 2014

                     Team Name  Matches Played  Matches Won  No Result  Points
0                 Punjab Kings              17           12          0      24
1        Kolkata Knight Riders              16           11          0      22
2          Chennai Super Kings              16           10          0      20
3               Mumbai Indians              15            7          0      14
4             Rajasthan Royals              14            7          0      14
5          Sunrisers Hyderabad              14            6          0      12
6  Royal Challengers Bangalore              14            5          0      10
7               Delhi Capitals              14            2          0       4

Season: 2015

                     Team Name  Matches Played  Matches Won  No Result  Points
0          Chennai Super Kings              17           10          0      20
1               Mumbai Indians              16           10          0      20
2  Royal Challengers Bangalore              16            8          2      18
3             Rajasthan Royals              14            7          1      15
4        Kolkata Knight Riders              13            7          0      14
5          Sunrisers Hyderabad              14            7          0      14
6               Delhi Capitals              14            5          1      11
7                 Punjab Kings              14            3          0       6

Season: 2016

                     Team Name  Matches Played  Matches Won  No Result  Points
0          Sunrisers Hyderabad              17           11          0      22
1                Gujarat Lions              16            9          0      18
2  Royal Challengers Bangalore              16            9          0      18
3        Kolkata Knight Riders              15            8          0      16
4               Delhi Capitals              14            7          0      14
5               Mumbai Indians              14            7          0      14
6       Rising Pune Supergiant              14            5          0      10
7                 Punjab Kings              14            4          0       8

Season: 2017

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Mumbai Indians              17           12          0      24
1       Rising Pune Supergiant              16           10          0      20
2        Kolkata Knight Riders              16            9          0      18
3          Sunrisers Hyderabad              14            8          0      16
4                 Punjab Kings              14            7          0      14
5               Delhi Capitals              14            6          0      12
6                Gujarat Lions              14            4          0       8
7  Royal Challengers Bangalore              13            3          0       6

Season: 2018

                     Team Name  Matches Played  Matches Won  No Result  Points
0          Chennai Super Kings              16           11          0      22
1          Sunrisers Hyderabad              17           10          0      20
2        Kolkata Knight Riders              16            9          0      18
3             Rajasthan Royals              15            7          0      14
4               Mumbai Indians              14            6          0      12
5                 Punjab Kings              14            6          0      12
6  Royal Challengers Bangalore              14            6          0      12
7               Delhi Capitals              14            5          0      10

Season: 2019

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Mumbai Indians              16           11          0      22
1          Chennai Super Kings              17           10          0      20
2               Delhi Capitals              16           10          0      20
3        Kolkata Knight Riders              14            6          0      12
4                 Punjab Kings              14            6          0      12
5          Sunrisers Hyderabad              15            6          0      12
6             Rajasthan Royals              14            5          1      11
7  Royal Challengers Bangalore              14            5          1      11

Season: 2020/21

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Mumbai Indians              16           11          0      22
1               Delhi Capitals              17            9          0      18
2          Sunrisers Hyderabad              16            8          0      16
3        Kolkata Knight Riders              14            7          0      14
4  Royal Challengers Bangalore              15            7          0      14
5          Chennai Super Kings              14            6          0      12
6                 Punjab Kings              14            6          0      12
7             Rajasthan Royals              14            6          0      12

Season: 2021

                     Team Name  Matches Played  Matches Won  No Result  Points
0          Chennai Super Kings              16           11          0      22
1               Delhi Capitals              16           10          0      20
2        Kolkata Knight Riders              17            9          0      18
3  Royal Challengers Bangalore              15            9          0      18
4               Mumbai Indians              14            7          0      14
5                 Punjab Kings              14            6          0      12
6             Rajasthan Royals              14            5          0      10
7          Sunrisers Hyderabad              14            3          0       6

Season: 2022

                     Team Name  Matches Played  Matches Won  No Result  Points
0               Gujarat Titans              16           12          0      24
1             Rajasthan Royals              17           10          0      20
2         Lucknow Super Giants              15            9          0      18
3  Royal Challengers Bangalore              16            9          0      18
4               Delhi Capitals              14            7          0      14
5                 Punjab Kings              14            7          0      14
6        Kolkata Knight Riders              14            6          0      12
7          Sunrisers Hyderabad              14            6          0      12
8          Chennai Super Kings              14            4          0       8
9               Mumbai Indians              14            4          0       8